
services:
  database:
    image: 'postgres:latest'
    container_name: 'mock-interview-db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: vishal
      POSTGRES_PASSWORD: vishal
      POSTGRES_DB: interview
    networks:
      - postgres-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  postgres-network:
    driver: bridge

volumes:
  db-data:
